export default [
  {
    id: 1,
    name: "الهام",
    location: "تهران",
    time: "05:23",
    date: "5 آبان",
    img: "./public/assets/1.jpg",
  },
  {
    id: 2,
    name: "زهرا",
    location: "تهران",
    time: "06:23",
    date: "11 مهر",
    img: "./public/assets/2.jpg",
  },
  {
    id: 3,
    name: "محمد",
    location: "اهواز",
    time: "05:23",
    date: "5 دی",
    img: "./public/assets/3.jpg",
  },
  {
    id: 4,
    name: "روشنک",
    location: "تهران",
    time: "05:23",
    date: "5 آبان",
    img: "./public/assets/1.jpg",
  },
  {
    id: 5,
    name: "بهناز",
    location: "تهران",
    time: "06:23",
    date: "11 مهر",
    img: "./public/assets/4.jpg",
  },
  {
    id: 6,
    name: "علی",
    location: "اهواز",
    time: "05:23",
    date: "5 دی",
    img: "./public/assets/5.jpg",
  },
];
